services:
  hexabot_server:
    container_name: hexabot_server
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
      - ./ros2_ws:/ros2_ws
    network_mode: service:husarnet
    stdin_open: true
    tty: true

  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file: "hexabot_server.env"
